---
title: "Data Cleaning"
author: "Tobias Iven"
date: "6/8/2020"
output: html_document
---

```{r}
library(readr)
sptext <- read_csv("All-seasons.csv")
#View(sptext)
library(stringr)
library(dplyr)
library(tidyr)
library(reshape2)
library(tuple)
```
```{r}
counts <- sptext %>%
  group_by(Character) %>%
  summarize(nlines = n()) %>%
  arrange(desc(nlines))
  
topcounts <- counts %>%
  filter(nlines >= 630)
  
topchar <- sptext %>%
  filter(Character %in% topcounts$Character) %>%
  mutate(cleanline = str_to_lower(str_remove_all(Line, "[^[:alnum:] ]"))) %>%
  select(Season, Episode, Character, cleanline)
  
ntopchar <- nrow(topcounts)

topcharnames <- topcounts$Character
```

```{r}
charlines <- topchar
write_csv(charlines, "charline.csv")
```

```{r}
rn <- nrow(charlines)
charwords <- data.frame()

for (i in 1:rn){
  
  currentline <- as.character(charlines[i,4])
  currentchar <- as.character(charlines[i,3])
  currentep <- as.numeric(charlines[i,2])
  currentseas <- as.numeric(charlines[i,1])
  
  words <- currentline %>%
    str_split(" ")
  
  words <- words[[1]]
  
  wordsl <- length(words)
  
  charl <- rep(currentchar, wordsl)
  epl <- rep(currentep, wordsl)
  seasl <- rep(currentseas, wordsl)
  
  datatobind <- data.frame(Season = seasl,
                           Episode = epl,
                           Character = charl,
                           words = words)
  
  charwords <- rbind(charwords, datatobind)
  
  
  if (i %% 1000 == 0){print(paste(i/rn * 100, "% done"))}
}
jj <- str_split("a b c d" , " ")
```


```{r}
charwords1 <- charwords %>%
  filter(words != "")
```

```{r}
write_csv(charwords1, "charwords.csv")
```

